import json

answers = json.loads("""
{"themes": [{"theme": "Prevalence of Obsessive-Compulsive Symptoms (OCS) in Schizophrenia",
   "items": ["71. Prevalence of Obsessive-Compulsive Symptoms (OCS) in Schizophrenia",
    "77. Prevalence of Obsessive-Compulsive Symptoms (OCS) in Schizophrenia",
    "82. Definition and Prevalence of Obsessive-Compulsive Symptoms (OCS) in Schizophrenia",
    "90. Prevalence of Obsessive-Compulsive Symptoms (OCS) and Disorder (OCD) in Schizophrenia",
    "114. Prevalence of Obsessive-Compulsive Symptoms (OCS) in Schizophrenia",
    "129. Prevalence of OCS and OCD in Schizophrenia",
    "133. Prevalence of Obsessive-Compulsive Symptoms (OCS) in Schizophrenia",
    "143. Definition and Prevalence of Obsessive-Compulsive Symptoms (OCS) in Schizophrenia",
    "154. Prevalence of Obsessive-Compulsive Symptoms (OCS) in Schizophrenia",
    "161. Prevalence of Obsessive-Compulsive Symptoms (OCS) in Clozapine-Treated Patients",
    "166. Prevalence of Obsessive-Compulsive Symptoms (OCS) in Schizophrenia",
    "174. Prevalence of OC Symptoms in Schizophrenia",
    "184. Prevalence of Obsessive-Compulsive Symptoms (OCS) in Schizophrenia"],
   "item_indices": [71,
    77,
    82,
    90,
    114,
    129,
    133,
    143,
    154,
    161,
    166,
    174,
    184]},
  {"theme": "Clozapine and Obsessive-Compulsive Symptoms (OCS)",
   "items": ["72. OCS and Clozapine Treatment",
    "78. Clozapine-Induced Onset of Obsessive-Compulsive Symptoms",
    "79. Correlation Between Clozapine Treatment and OCS Severity",
    "80. Pathogenetic Mechanisms of OCS Induction by Clozapine",
    "83. Obsessive-Compulsive Symptoms (OCS) and Clozapine Treatment",
    "85. Complex Relationship Between Clozapine and OCS",
    "86. Pre-existing OCS and Clozapine Treatment",
    "89. Impact of Clozapine on OCS",
    "91. Mechanism of Clozapine-Induced OCS/OCD",
    "92. De Novo Emergence of OCS/OCD with Clozapine",
    "93. Course and Management of OCS/OCD Induced by Clozapine",
    "94. Prevalence and Impact of OCS in Clozapine-Treated Patients",
    "113. Clozapine and Obsessive-Compulsive Symptoms",
    "115. Clozapine's Role in Inducing Obsessive-Compulsive Symptoms (OCS)",
    "119. Clozapine and Obsessive-Compulsive Symptoms (OCS)",
    "122. Clozapine-induced OCS Mechanism",
    "123. Clozapine-induced OCS Management",
    "124. Clozapine-induced OCS and Genetic Factors",
    "125. Clozapine-induced OCS in Non-Psychotic Patients",
    "126. Clozapine and Antiserotonergic Antipsychotics",
    "128. Clozapine-induced OCS and Serotonin Levels",
    "134. Mechanism of Clozapine-Induced OCS",
    "135. Prevalence of Clozapine-Associated OCS",
    "136. Severity of Clozapine-Associated OCS",
    "137. Management Strategies for Clozapine-Associated OCS",
    "138. Effectiveness of Antidepressants in Managing Clozapine-Associated OCS",
    "139. Impact of Clozapine Dose on OCS Severity",
    "140. Role of Aripiprazole in Managing Clozapine-Associated OCS",
    "141. Management of Clozapine-Associated OCS",
    "142. Non-Pharmacological Treatments for Clozapine-Associated OCS",
    "155. Clozapine's Mechanism in Inducing OCS",
    "156. Role of Dopamine in Clozapine-Induced OCS",
    "157. Genetic Factors in Clozapine-Induced OCS",
    "158. Treatment Options for Clozapine-Induced OCS",
    "165. Mechanism of Clozapine-Induced Habit Formation",
    "185. Association of Clozapine with Obsessive-Compulsive Symptoms (OCS)",
    "186. Mechanisms of Clozapine-Induced OCS",
    "187. Impact of Clozapine-Induced OCS on Disability",
    "188. Phenomenology of Clozapine-Induced OCS",
    "189. Correlation Between OCS Severity and Clinical Variables"],
   "item_indices": [72,
    78,
    79,
    80,
    83,
    85,
    86,
    89,
    91,
    92,
    93,
    94,
    113,
    115,
    119,
    122,
    123,
    124,
    125,
    126,
    128,
    134,
    135,
    136,
    137,
    138,
    139,
    140,
    141,
    142,
    155,
    156,
    157,
    158,
    165,
    185,
    186,
    187,
    188,
    189]},
  {"theme": "Impact of Clozapine Dose on OCS and OCD",
   "items": ["132. Impact of Clozapine Dose on OCS and OCD",
    "139. Impact of Clozapine Dose on OCS Severity"],
   "item_indices": [132, 139]},
  {"theme": "Management and Treatment of Clozapine-Associated OCS",
   "items": ["93. Course and Management of OCS/OCD Induced by Clozapine",
    "123. Clozapine-induced OCS Management",
    "137. Management Strategies for Clozapine-Associated OCS",
    "138. Effectiveness of Antidepressants in Managing Clozapine-Associated OCS",
    "140. Role of Aripiprazole in Managing Clozapine-Associated OCS",
    "141. Management of Clozapine-Associated OCS",
    "142. Non-Pharmacological Treatments for Clozapine-Associated OCS",
    "158. Treatment Options for Clozapine-Induced OCS"],
   "item_indices": [93, 123, 137, 138, 140, 141, 142, 158]},
  {"theme": "Genetic and Neurobiological Factors in OCS and OCD",
   "items": ["124. Clozapine-induced OCS and Genetic Factors",
    "156. Role of Dopamine in Clozapine-Induced OCS",
    "157. Genetic Factors in Clozapine-Induced OCS",
    "164. Genetic Moderators of Obsessions and Compulsions",
    "175. Role of Glutamate in OCD Pathophysiology",
    "176. Association of SLC1A1 with OCD",
    "177. Association of GRIN2B with OCD",
    "178. Association of GRIK2 with OCD",
    "179. Interaction Between SLC1A1 and GRIN2B",
    "180. Association of SLC1A1 Polymorphism with OCD",
    "181. Association of GRIN2B Polymorphism with OCD",
    "182. Association of GRIK2 Polymorphism with OCD"],
   "item_indices": [124,
    156,
    157,
    164,
    175,
    176,
    177,
    178,
    179,
    180,
    181,
    182]}]}
""")
