{
    "themes": [
        {
            "items": [
                "71. Prevalence of Obsessive-Compulsive Symptoms (OCS) in Schizophrenia",
                "77. Prevalence of Obsessive-Compulsive Symptoms (OCS) in Schizophrenia",
                "82. Definition and Prevalence of Obsessive-Compulsive Symptoms (OCS) in Schizophrenia",
                "90. Prevalence of Obsessive-Compulsive Symptoms (OCS) and Disorder (OCD) in Schizophrenia",
                "129. Prevalence of OCS and OCD in Schizophrenia",
                "133. Prevalence of Obsessive-Compulsive Symptoms (OCS) in Schizophrenia",
                "144. Prevalence of OCD in Schizophrenia",
                "154. Prevalence of Obsessive-Compulsive Symptoms (OCS) in Schizophrenia",
                "161. Prevalence of Obsessive-Compulsive Symptoms (OCS) in Clozapine-Treated Patients",
                "184. Prevalence of Obsessive-Compulsive Symptoms (OCS) in Schizophrenia",
            ],
            "theme": "Prevalence of Obsessive-Compulsive Symptoms (OCS) in Schizophrenia",
            "item_indices": [71, 77, 82, 90, 129, 133, 144, 154, 161, 184],
        },
        {
            "items": [
                "72. OCS and Clozapine Treatment",
                "78. Clozapine-Induced Onset of Obsessive-Compulsive Symptoms",
                "83. Obsessive-Compulsive Symptoms (OCS) and Clozapine Treatment",
                "115. Clozapine's Role in Inducing Obsessive-Compulsive Symptoms (OCS)",
                "119. Clozapine and Obsessive-Compulsive Symptoms (OCS)",
                "122. Clozapine-induced OCS Mechanism",
                "123. Clozapine-induced OCS Management",
                "124. Clozapine-induced OCS and Genetic Factors",
                "125. Clozapine-induced OCS in Non-Psychotic Patients",
                "128. Clozapine-induced OCS and Serotonin Levels",
                "134. Mechanism of Clozapine-Induced OCS",
                "135. Prevalence of Clozapine-Associated OCS",
                "136. Severity of Clozapine-Associated OCS",
                "137. Management Strategies for Clozapine-Associated OCS",
                "138. Effectiveness of Antidepressants in Managing Clozapine-Associated OCS",
                "139. Impact of Clozapine Dose on OCS Severity",
                "141. Management of Clozapine-Associated OCS",
                "158. Treatment Options for Clozapine-Induced OCS",
                "186. Mechanisms of Clozapine-Induced OCS",
                "187. Impact of Clozapine-Induced OCS on Disability",
                "188. Phenomenology of Clozapine-Induced OCS",
            ],
            "theme": "Clozapine-Induced OCS",
            "item_indices": [
                72,
                78,
                83,
                115,
                119,
                122,
                123,
                124,
                125,
                128,
                134,
                135,
                136,
                137,
                138,
                139,
                141,
                158,
                186,
                187,
                188,
            ],
        },
        {
            "items": [
                "84. Risk Factors for Developing De Novo OCS",
                "102. Risk Factors for Developing OCS",
                "130. Risk Factors for OCS and OCD in Schizophrenia",
                "131. Association Between Dyslipidemia and OCS/OCD",
            ],
            "theme": "Risk Factors and Comorbidity",
            "item_indices": [84, 102, 130, 131],
        },
        {
            "items": [
                "73. Symptom Profile Differences Between OCD and Schizophrenia with OCS",
                "87. Obsessions and Compulsions in Schizophrenia",
                "96. Impact of OCS on Wellbeing Independently of Depression and Psychosis",
                "100. OCS and General Functioning",
                "101. Impact of OCS on Subjective Wellbeing",
                "153. Impact of OCD on Clinical Function",
                "170. Risk Assessment Before Treating Harm Obsessions",
                "171. Symptom Reduction Through CBT",
            ],
            "theme": "Symptoms and Functionality",
            "item_indices": [73, 87, 96, 100, 101, 153, 170, 171],
        },
        {
            "items": [
                "93. Course and Management of OCS/OCD Induced by Clozapine",
                "140. Role of Aripiprazole in Managing Clozapine-Associated OCS",
                "142. Non-Pharmacological Treatments for Clozapine-Associated OCS",
                "169. CBT for OCS and Schizophrenia",
                "172. Therapeutic Approach and Engagement",
                "173. Improvements and Limitations",
            ],
            "theme": "Management Strategies for OCS",
            "item_indices": [93, 140, 142, 169, 172, 173],
        },
        {
            "items": [
                "98. Longitudinal Study Strengths and Limitations",
                "99. Clinician Awareness and Reporting of OCS",
                "103. Measurement Tools and Their Validity",
            ],
            "theme": "Measurement and Assessment",
            "item_indices": [98, 99, 103],
        },
        {
            "items": [
                "116. Impact of Fluvoxamine on Clozapine Serum Levels",
                "117. Dose-Dependent Side Effects of Clozapine",
                "104. Clozapine's Pharmacodynamics and Mechanism of Action",
                "105. Clozapine's Pharmacokinetics and Metabolism",
                "106. Clozapine's Variable Pharmacokinetics",
                "107. Clozapine's Therapeutic Drug Monitoring",
                "108. Clozapine and Cardiovascular Effects",
                "109. Clozapine and Neurological Effects",
                "110. Clozapine and Metabolic Effects",
                "111. Clozapine and Extrapyramidal Symptoms",
                "112. Clozapine and Gastrointestinal Effects",
                "156. Role of Dopamine in Clozapine-Induced OCS",
                "160. Complex Serotonin-Dopamine Mechanisms",
                "167. Clozapine's Efficacy and Side Effects",
            ],
            "theme": "Drug Interactions and Pharmacology",
            "item_indices": [116, 117, 104, 105, 106, 107, 108, 109, 110, 111, 112, 156, 160, 167],
        },
        {
            "items": [
                "124. Clozapine-induced OCS and Genetic Factors",
                "157. Genetic Factors in Clozapine-Induced OCS",
                "176. Association of SLC1A1 with OCD",
                "177. Association of GRIN2B with OCD",
                "178. Association of GRIK2 with OCD",
                "179. Interaction Between SLC1A1 and GRIN2B",
                "180. Association of SLC1A1 Polymorphism with OCD",
                "181. Association of GRIN2B Polymorphism with OCD",
                "182. Association of GRIK2 Polymorphism with OCD",
            ],
            "theme": "Genetic Factors and Associations",
            "item_indices": [124, 157, 176, 177, 178, 179, 180, 181, 182],
        },
    ]
}
